# application-template.yml - auth-server

server:
  port: 8888  # auth-server

spring:
  application:
    name: auth-server
  datasource:
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000  # 토큰 만료 시간 (밀리초 기준, 1시간)
      refresh-expiration: 604800000 # 리프레시 토큰 만료 시간 (밀리초 기준, 7일)

grpc:
  server:
    port: 50051  # gRPC 서버가 사용할 포트 번호

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Spring Security 관련 로그 디버깅 설정

