# application-template.yml - resource-server

server:
  port: 9999  # resource-server

spring:
  application:
    name: resource-server
  datasource:
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  server:
    port: 50052  # gRPC 서버가 사용할 포트 번호

logging:
  level:
    root: INFO  # 로그 디버깅
    io.grpc: DEBUG  # gRPC 관련 로그 디버깅 설정
